# name: Python

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "25 */1 * * *"
#   push:
#     branches: ["main"]

# jobs:
#   run:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - name: Checkout do código
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.12"

#       - name: Instalar dependências
#         run: |
#           python -m pip install --upgrade pip --quiet
#           if [ -f requirements.txt ]; then pip install -r requirements.txt --quiet; fi

#       - name: Executar script Python
#         env:
#           URL: ${{ secrets.URL }}
#           URL_NFT: ${{ secrets.URL_NFT }}
#           TOKENS_NFT: ${{ secrets.TOKENS_NFT }}
#           DEVICE_ID: ${{ secrets.DEVICE_ID }}
#           LANG_COUNTRY: ${{ secrets.LANG_COUNTRY }}
#           WALLET: ${{ secrets.WALLET }}
#           WALLET_S: ${{ secrets.WALLET_S }}
#           URL_LOGIN_TAP: ${{ secrets.URL_LOGIN_TAP }}
#           URL_CLAIM_TAP: ${{ secrets.URL_CLAIM_TAP }}
#           HEADER1_TAP: ${{ secrets.HEADER1_TAP }}
#           HEADER2_TAP: ${{ secrets.HEADER2_TAP }}
#           PAYLOAD_LOGIN_TAP: ${{ secrets.PAYLOAD_LOGIN_TAP }}
#           TOKENS_CLOUD: ${{ secrets.TOKENS_CLOUD }}
#         timeout-minutes: 10
#         run: |
#           echo ""
#           echo "========== CLOUD =========="
#           echo ""
#           python app.py || echo "app.py falhou"
#           echo ""
#           echo "========== TAP =========="
#           echo ""
#           python app2.py
#           echo ""
